BHBq/Controllers/CompteBancaireController.cs
using System.Diagnostics;
using BHBq.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BHBq.Controllers
{
    public class CompteBancaireController : Controller
    {
        private readonly BHBqContext _context;
        public List<CompteBancaire> comptesBancaires { get; set; }
        public EntrepriseViewModel Listes { get; set; }

        public CompteBancaireController()
        {
            var options = new DbContextOptionsBuilder<BHBqContext>()
                .UseSqlite($"Data Source=BHBq.db")
                .Options;

            _context = new BHBqContext(options);
            Listes = new EntrepriseViewModel();
        }

        // GET: Tous les comptes bancaires
        public IActionResult ComptesBancaires(int idEntreprise)
        {
            Listes.TargetEntreprise = _context.Entreprises.Find(idEntreprise);

            return View(Listes);
        }

        [HttpPost]
        public async Task<IActionResult> EditCompteBancaire(int id, CompteBancaire compteBancaire)
        {
            var existingCompteBancaire = await _context.ComptesBancaires.FindAsync(id);

            if (existingCompteBancaire == null)
            {
                return NotFound();
            }

            // Mettre à jour les propriétés non nulles de l'objet existant
            if (compteBancaire.IdEntreprise != null)
            {
                existingCompteBancaire.IdEntreprise = compteBancaire.IdEntreprise;
            }
            if (!string.IsNullOrEmpty(compteBancaire.Adresse))
            {
                existingCompteBancaire.Adresse = compteBancaire.Adresse;
            }
            if (!string.IsNullOrEmpty(compteBancaire.IBAN))
            {
                existingCompteBancaire.IBAN = compteBancaire.IBAN;
            }
            if (!string.IsNullOrEmpty(compteBancaire.BIC))
            {
                existingCompteBancaire.BIC = compteBancaire.BIC;
            }
            if (!string.IsNullOrEmpty(compteBancaire.NumCompte))
            {
                existingCompteBancaire.NumCompte = compteBancaire.NumCompte;
            }
            if (!string.IsNullOrEmpty(compteBancaire.NomBanque))
            {
                existingCompteBancaire.NomBanque = compteBancaire.NomBanque;
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("ComptesBancaires", new { idEntreprise = compteBancaire.IdEntreprise });
        }

        [HttpPost]
        public async Task<IActionResult> NewCompteBancaire(CompteBancaire compteBancaire)
        {

            await _context.ComptesBancaires.AddAsync(compteBancaire);
            await _context.SaveChangesAsync();
            return RedirectToAction("ComptesBancaires", new { idEntreprise = compteBancaire.IdEntreprise });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCompteBancaire(int id)
        {
            var existingCompteBancaire = await _context.ComptesBancaires.FindAsync(id);

            if (existingCompteBancaire == null)
            {
                return NotFound();
            }

            _context.ComptesBancaires.Remove(existingCompteBancaire);
            await _context.SaveChangesAsync();

            return RedirectToAction("ComptesBancaires", new { idEntreprise = existingCompteBancaire.IdEntreprise });
        }
    }
}

BHBq/Controllers/EntrepriseController.cs
using System.Diagnostics;
using BHBq.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BHBq.Controllers;

public class EntrepriseController : Controller
{
    private readonly BHBqContext _context;
    public List<Entreprise> entreprises { get; set; }
    public EntrepriseViewModel Listes { get; set; }

    public EntrepriseController()
    {
        var options = new DbContextOptionsBuilder<BHBqContext>()
            .UseSqlite($"Data Source=BHBq.db")
            .Options;

        _context = new BHBqContext(options);
        Listes = new EntrepriseViewModel();
    }

    //Get toutes les entreprises
    public IActionResult Entreprises()
    {
        return View(Listes);
    }

    [HttpPost]
    public async Task<IActionResult> EditEntreprise(int id, Entreprise entreprise)
    {
        var existingEntreprise = await _context.Entreprises.FindAsync(id);

        if (existingEntreprise == null)
        {
            return NotFound();
        }

        // Mettre à jour les propriétés non nulles de l'objet existant
        if (!string.IsNullOrEmpty(entreprise.NomEntreprise))
        {
            existingEntreprise.NomEntreprise = entreprise.NomEntreprise;
        }
        if (!string.IsNullOrEmpty(entreprise.Siret))
        {
            existingEntreprise.Siret = entreprise.Siret;
        }
        if (!string.IsNullOrEmpty(entreprise.Statut))
        {
            existingEntreprise.Statut = entreprise.Statut;
        }
        if (!string.IsNullOrEmpty(entreprise.Activite))
        {
            existingEntreprise.Activite = entreprise.Activite;
        }
        if (!string.IsNullOrEmpty(entreprise.Siege))
        {
            existingEntreprise.Siege = entreprise.Siege;
        }
        if (!string.IsNullOrEmpty(entreprise.APE))
        {
            existingEntreprise.APE = entreprise.APE;
        }
        existingEntreprise.Description = entreprise.Description;

        await _context.SaveChangesAsync();
        return RedirectToAction("Entreprises");
    }

    [HttpPost]
    public async Task<IActionResult> NewEntreprise(Entreprise entreprise)
    {
        if (!long.TryParse(entreprise.Siret, out _))
        {
            return RedirectToAction(
                "Error",
                "Error",
                new { Message = "Le siret doit être un nombre entier !" }
            );
        }
        else if (
            // Vérifie si les quatre premiers caractères sont des chiffres
            // Vérifie si le cinquième caractère est une lettre
            !char.IsDigit(entreprise.APE[0])
            || !char.IsDigit(entreprise.APE[1])
            || !char.IsDigit(entreprise.APE[2])
            || !char.IsDigit(entreprise.APE[3])
            || !char.IsLetter(entreprise.APE[4])
        )
        {
            return RedirectToAction(
                "Error",
                "Error",
                new { Message = "Le code APE rentré n'est pas au bon format !" }
            );
        }
        else
        {
            await _context.Entreprises.AddAsync(entreprise);
            await _context.SaveChangesAsync();
            return RedirectToAction("Entreprises");
        }
    }

    [HttpPost]
    public async Task<IActionResult> DeleteEntreprise(int id)
    {
        var existingEntreprise = await _context.Entreprises.FindAsync(id);

        if (existingEntreprise == null)
        {
            return NotFound();
        }

        _context.Entreprises.Remove(existingEntreprise);
        await _context.SaveChangesAsync();

        return RedirectToAction("Entreprises");
    }
}

BHBq/Controllers/LotController.cs
using System.Data;
using System.Diagnostics;
using BHBq.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BHBq.Controllers;

public class LotController : Controller
{
    private readonly BHBqContext _context;
    public LotsViewModel Listes { get; set; }

    public LotController()
    {
        var options = new DbContextOptionsBuilder<BHBqContext>()
            .UseSqlite($"Data Source=BHBq.db")
            .Options;

        _context = new BHBqContext(options);
        Listes = new LotsViewModel();
    }

    //Get toutes les Lots
    public IActionResult Lots(int idEntreprise)
    {
        Listes.Entreprise = _context.Entreprises.Find(idEntreprise);

        var listeParams = _context
            .Parametres.Select(e => new SelectListItem { Text = e.Nom, Value = e.Id.ToString() })
            .ToList();
        Listes.ListeParams = listeParams;

        return View(Listes);
    }

    [HttpPost]
    public async Task<IActionResult> EditLot(int id, Lot Lot)
    {
        var existingLot = await _context.Lots.FindAsync(id);

        if (existingLot == null)
        {
            return NotFound();
        }

        // Copy the values from the Lot object to the existing object only if the properties are not null
        if (Lot.Designation != null)
        {
            existingLot.Designation = Lot.Designation;
        }
        if (Lot.IdLot != null)
        {
            existingLot.IdLot = Lot.IdLot;
        }
        if (Lot.CoefPose != null)
        {
            existingLot.CoefPose = Lot.CoefPose;
        }
        await _context.SaveChangesAsync();
        return RedirectToAction("Lots", new { idEntreprise = Lot.IdEntreprise });
    }

    [HttpPost]
    public async Task<IActionResult> NewLot(Lot lot)
    {
        // Si le lot existe déjà, retourner une erreur
        var existingLots = await _context.Lots.AnyAsync(l => l.IdLot == lot.IdLot);

        if (existingLots)
        {
            return RedirectToAction(
                "Error",
                "Error",
                new { Message = $"Le lot {lot.IdLot} existe deja !" }
            );
        }
        else
        {
            await _context.Lots.AddAsync(lot);
            await _context.SaveChangesAsync();
            return RedirectToAction("Lots", new { idEntreprise = lot.IdEntreprise });
        }
    }

    [HttpPost]
    public async Task<IActionResult> DeleteLot(int id)
    {
        var existingLot = await _context.Lots.FindAsync(id);

        if (existingLot == null)
        {
            return NotFound();
        }

        // Supprimer tous les lots commençant par IdLot. de l'entrée
        var lotsToDelete = _context.Lots.Where(l => l.IdLot.StartsWith(existingLot.IdLot));
        var articlesToDelete = _context.Articles.Where(a => lotsToDelete.Any(l => l.Id == a.IdLot));

        _context.Lots.RemoveRange(lotsToDelete);
        _context.Articles.RemoveRange(articlesToDelete);
        await _context.SaveChangesAsync();

        return RedirectToAction("Lots", new { idEntreprise = existingLot.IdEntreprise });
    }

    [HttpPost]
    public async Task<IActionResult> NewArticle(Article article, int IdEntreprise)
    {
        await _context.Articles.AddAsync(article);
        await _context.SaveChangesAsync();
        return RedirectToAction("Lots", new { idEntreprise = IdEntreprise });
    }

    [HttpPost]
    public async Task<IActionResult> DeleteArticle(int id, int IdEntreprise)
    {
        var existingArticle = await _context.Articles.FindAsync(id);

        if (existingArticle == null)
        {
            return NotFound();
        }

        _context.Articles.Remove(existingArticle);
        ;
        await _context.SaveChangesAsync();

        return RedirectToAction("Lots", new { idEntreprise = IdEntreprise });
    }

    [HttpPost]
    public async Task<IActionResult> EditArticle(int id, int IdEntreprise, Article article)
    {
        var existingArticle = await _context.Articles.FindAsync(id);

        if (existingArticle == null)
        {
            return NotFound();
        }

        // Copy the values from the Article object to the existing object only if the properties are not null
        if (article.Libelle != null)
        {
            existingArticle.Libelle = article.Libelle;
        }
        if (article.IdLot != null)
        {
            existingArticle.IdLot = article.IdLot;
        }
        if (article.Unite != null)
        {
            existingArticle.Unite = article.Unite;
        }
        if (article.PrixH != null)
        {
            existingArticle.PrixH = article.PrixH;
        }
        if (article.PrixM != null)
        {
            existingArticle.PrixM = article.PrixM;
        }
        if (article.PrixB != null)
        {
            existingArticle.PrixB = article.PrixB;
        }
        if (article.Calcul != null)
        {
            existingArticle.Calcul = article.Calcul;
        }
        await _context.SaveChangesAsync();
        return RedirectToAction("Lots", new { idEntreprise = IdEntreprise });
    }

    public async Task<IActionResult> EditCalcul(
        int id,
        int IdEntreprise,
        Article article,
        int param1,
        int param2,
        int param3,
        int param4
    )
    {
        var existingArticle = await _context.Articles.FindAsync(id);

        try
        {
            string calculation = string.Format(article.Calcul, 1, 1, 1, 1);
            DataTable table = new DataTable();
            double result = Convert.ToDouble(table.Compute(calculation, String.Empty));
        }
        catch (Exception e)
        {
            return RedirectToAction("Error", "Error", new { Message = e.Message });
        }

        article.FormatCalcul = article.Calcul;

        if (param1 != 0)
        {
            var param1Article = await _context.Parametres.FindAsync(param1);
            article.FormatCalcul = article.FormatCalcul.Replace(
                "{0}",
                "{" + $"{param1Article.Nom}" + "}"
            );
        }
        if (param2 != 0)
        {
            var param2Article = await _context.Parametres.FindAsync(param2);
            article.FormatCalcul = article.FormatCalcul.Replace(
                "{1}",
                "{" + $"{param2Article.Nom}" + "}"
            );
        }
        if (param3 != 0)
        {
            var param3Article = await _context.Parametres.FindAsync(param3);
            article.FormatCalcul = article.FormatCalcul.Replace(
                "{2}",
                "{" + $"{param3Article.Nom}" + "}"
            );
        }
        if (param4 != 0)
        {
            var param4Article = await _context.Parametres.FindAsync(param4);
            article.FormatCalcul = article.FormatCalcul.Replace(
                "{3}",
                "{" + $"{param4Article.Nom}" + "}"
            );
        }

        article.Calcul = article.Calcul.Replace("{0}", "{" + $"{param1}" + "}");
        article.Calcul = article.Calcul.Replace("{1}", "{" + $"{param2}" + "}");
        article.Calcul = article.Calcul.Replace("{2}", "{" + $"{param3}" + "}");
        article.Calcul = article.Calcul.Replace("{3}", "{" + $"{param4}" + "}");

        if (existingArticle == null)
        {
            return NotFound();
        }

        if (article.Calcul != null)
        {
            existingArticle.Calcul = article.Calcul;
        }
        if (article.FormatCalcul != null)
        {
            existingArticle.FormatCalcul = article.FormatCalcul;
        }
        await _context.SaveChangesAsync();
        return RedirectToAction("Lots", new { idEntreprise = IdEntreprise });
    }
}

BHBq/Views/Shared/EntreprisePartial/EditEntreprise.cshtml
@model EntrepriseViewModel
@{
    string modalId = $"myModal-{Model.TargetEntreprise.Id}";
}

<div class="info-box card">
    <div class="row">
        <div class="col">
            <i class="bi bi-geo-alt"></i>
            <h3>@Model.TargetEntreprise.NomEntreprise</h3>
        </div>
        <div class="col text-end">
            <!-- Delete -->
            <button type="button" class="btn btn-lg" data-bs-toggle="modal"
                data-bs-target="#deleteModal-@Model.TargetEntreprise.Id">
                <i class="ri-delete-bin-2-line fs-2"></i>
            </button>

            <!-- Modal -->
            <div class="modal fade" id="deleteModal-@Model.TargetEntreprise.Id" tabindex="-1"
                aria-labelledby="deleteModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel">Confirmation de suppression</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body text-center">
                            Êtes-vous sûr de vouloir supprimer cette entreprise ?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                            <form asp-area="" asp-controller="Entreprise" asp-action="DeleteEntreprise"
                                asp-route-id="@Model.TargetEntreprise.Id" method="post">
                                <button type="submit" class="btn btn-danger">Supprimer</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-lg-6 col-md-6 justify-content-center">
            <div class="row m-2">
                <div class="col-lg-6 col-md-6 label text-end">
                    <h5>Statut :</h5>
                </div>
                <div class="col-lg-6 col-md-6">@Model.TargetEntreprise.Statut</div>
            </div>

            <div class="row m-2">
                <div class="col-lg-6 col-md-6 text-end">
                    <h5>Activité :</h5>
                </div>
                <div class="col-lg-6 col-md-6">@Model.TargetEntreprise.Activite</div>
            </div>

            <div class="row m-2">
                <div class="col-lg-6 col-md-6 text-end">
                    <h5>Siège :</h5>
                </div>
                <div class="col-lg-6 col-md-6">@Model.TargetEntreprise.Siege</div>
            </div>
        </div>

        <div class="col-lg-6 col-md-6 justify-content-center">
            <div class="row m-2">
                <div class="col-lg-6 col-md-6 label text-end">
                    <h5>Code APE :</h5>
                </div>
                <div class="col-lg-6 col-md-6">@Model.TargetEntreprise.APE</div>
            </div>

            <div class="row m-2">
                <div class="col-lg-6 col-md-6 text-end">
                    <h5>N° SIRET :</h5>
                </div>
                <div class="col-lg-6 col-md-6">@Model.TargetEntreprise.Siret</div>
            </div>
        </div>
    </div>

    @if (Model.TargetEntreprise.Description != null)
    {
        <h5>Description</h5>
        <p class="small fst-italic">@Model.TargetEntreprise.Description</p>
    }

    <div class="row mt-4">
        <div class="col">
            <div class="btn-group" role="group" aria-label="Actions">
                <a class="btn btn-outline-secondary btn-sm" asp-controller="CompteBancaire"
                    asp-action="ComptesBancaires" asp-route-idEntreprise="@Model.TargetEntreprise.Id">Comptes
                    bancaires</a>
                <a class="btn btn-outline-secondary btn-sm" asp-area="" asp-controller="Lot" asp-action="Lots"
                    asp-route-idEntreprise="@Model.TargetEntreprise.Id">Lots</a>
            </div>
        </div>
        <div class="col">
            <div class="text-end">
                <button class="btn btn-outline-secondary btn-sm" type="button" data-bs-toggle="modal"
                    data-bs-target="#@modalId">Modifier</button>
            </div>
        </div>
    </div>

    <div class="modal fade" id="@modalId" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Mise à jour des informations de @Model.TargetEntreprise.NomEntreprise</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="post" class="row needs-validation g-3" asp-controller="Entreprise" asp-action="EditEntreprise" novalidate
                        asp-route-Id="@Model.TargetEntreprise.Id">
                        <div class="col-md-12">
                            <input asp-for="@Model.TargetEntreprise.NomEntreprise" maxlength="20" type="text"
                                class="form-control" placeholder="Nom de l'entreprise" name="nomEntreprise"
                                pattern="[A-Z-]+"
                                title="Veuillez fournir un nom d'entreprise en majuscules avec éventuellement des tirets (-)"
                                required>
                            <div class="invalid-feedback" for="nomEntreprise">
                                Veuillez fournir un nom d'entreprise en majuscules avec éventuellement des tirets (-).
                            </div>
                        </div>
                        <div class="col-md-6">
                            <input asp-for="@Model.TargetEntreprise.Siege" type="text" class="form-control"
                                placeholder="Siège" name="siege" pattern="[A-Za-z0-9\s]{1,100}" required>
                            <div class="invalid-feedback" for="siege">
                                Veuillez fournir une adresse de siège valide.
                            </div>
                        </div>
                        <div class="col-md-6">
                            <select asp-for="@Model.TargetEntreprise.Statut" class="form-control" name="statut"
                                id="statut" required>
                                <option value="">Sélectionnez un statut</option>
                                <option value="SAS">SAS</option>
                                <option value="SARL">SARL</option>
                                <option value="SA">SA</option>
                                <option value="EI">EI</option>
                                <option value="EURL">EURL</option>
                                <option value="SNC">SNC</option>
                                <option value="SCOP">SCOP</option>
                                <option value="SC">SC</option>
                                <option value="GIE">GIE</option>
                                <option value="Autre">Autre</option>
                            </select>
                            <div class="invalid-feedback" for="statut">
                                Veuillez sélectionner un statut.
                            </div>
                        </div>
                        <div class="col-md-12">
                            <input asp-for="@Model.TargetEntreprise.Activite" type="text" class="form-control"
                                placeholder="Activité" name="activite" required>
                            <div class="invalid-feedback" for="activite">
                                Veuillez fournir une activité valide.
                            </div>
                        </div>
                        <div class="col-md-6">
                            <input asp-for="@Model.TargetEntreprise.Siret" pattern="[0-9]{14}" type="text"
                                class="form-control" placeholder="SIRET" minlength="14" maxlength="14" name="siret" required>
                            <div class="invalid-feedback" for="siret">
                                Veuillez fournir un code SIRET valide (14 chiffres).
                            </div>
                        </div>
                        <div class="col-md-6">
                            <input asp-for="@Model.TargetEntreprise.APE" type="text" pattern="[0-9]{4}[A-Z]{1}"
                                class="form-control" placeholder="APE" name="ape" required>
                            <div class="invalid-feedback" for="ape">
                                Veuillez fournir un code APE valide (4 chiffres et 1 lettre majuscule).
                            </div>
                        </div>

                        <div class="col-12">
                            <div class="form-floating">
                                <textarea asp-for="@Model.TargetEntreprise.Description" class="form-control"
                                    id="floatingTextarea" name="description" style="height: 100px;"></textarea>
                                <label for="floatingTextarea">Description</label>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Abandonner</button>
                            <button type="submit" class="btn btn-success">Sauvegarder</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div><!-- Fin du Modal centré verticalement -->
</div>