BHBq/Models/Document.cs
public class Document
{
    public int Id { get; set; }
    public int Type { get; set; }
    public int IdProjet { get; set; }
    public int IdAcompte { get; set; }
    public int IdTVA { get; set; }
    public int IdEntreprise { get; set; }
    public bool Escompte { get; set; }
    public int Origine { get; set; }
    public string Num { get; set; }

    public Document()
    {
        // Empty constructor
    }

    public Document(int type, int idProjet, int idAcompte, int idTVA, int idEntreprise, bool escompte, int origine, string num)
    {
        Type = type;
        IdProjet = idProjet;
        IdAcompte = idAcompte;
        IdTVA = idTVA;
        IdEntreprise = idEntreprise;
        Escompte = escompte;
        Origine = origine;
        Num = num;
    }
}

BHBq/Controllers/ClientController.cs
using System.Diagnostics;
using BHBq.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BHBq.Controllers;

public class ClientController : Controller
{
    private readonly BHBqContext _context;
    public ClientViewModel Listes { get; set; }

    public ClientController()
    {
        var options = new DbContextOptionsBuilder<BHBqContext>()
            .UseSqlite($"Data Source=BHBq.db")
            .Options;

        _context = new BHBqContext(options);
        Listes = new ClientViewModel();
    }

    //Get toutes les clients
    public IActionResult Clients()
    {
        return View(Listes);
    }

    [HttpPost]
    public async Task<IActionResult> EditClient(int id, Client client, int Categorie)
    {
        var existingClient = await _context.Clients.FindAsync(id);

        if (existingClient == null)
        {
            return NotFound();
        }

        // Mettre à jour les propriétés non nulles de l'objet existant
        if (!string.IsNullOrEmpty(client.Nom))
        {
            existingClient.Nom = client.Nom;
        }
        if (!string.IsNullOrEmpty(client.Adresse))
        {
            existingClient.Adresse = client.Adresse;
        }
        if (client.Categorie!=null)
        {
            existingClient.Categorie = Categorie == 1;
            if (client.Categorie == false)
            {
                existingClient.Siret = null;
                existingClient.TvaIntracom = null;
            }
        }

        // Mettre à jour les propriétés spécifiques aux professionnels
        if (client.Categorie == true)
        {
            if (!string.IsNullOrEmpty(client.Siret))
            {
                existingClient.Siret = client.Siret;
            }
            if (!string.IsNullOrEmpty(client.TvaIntracom))
            {
                existingClient.TvaIntracom = client.TvaIntracom;
            }
        }

        await _context.SaveChangesAsync();
        return RedirectToAction("Clients");
    }

    [HttpPost]
    public async Task<IActionResult> NewClient(Client client, int Categorie)
    {
        client.Categorie = Categorie == 1;
        await _context.Clients.AddAsync(client);
        await _context.SaveChangesAsync();
        return RedirectToAction("Clients");
    }

    [HttpPost]
    public async Task<IActionResult> DeleteClient(int id)
    {
        var existingClient = await _context.Clients.FindAsync(id);

        if (existingClient == null)
        {
            return NotFound();
        }

        // Supprimer tous les projets avec des IdClient égaux à id
        var projectsToDelete = await _context.Projets.Where(p => p.IdClient == id).ToListAsync();
        _context.Projets.RemoveRange(projectsToDelete);

        _context.Clients.Remove(existingClient);
        await _context.SaveChangesAsync();

        return RedirectToAction("Clients");
    }
    }

BHBq/Controllers/DashboardController.cs
using System.Diagnostics;
using BHBq.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BHBq.Controllers;

public class DashboardController : Controller
{
    private readonly ILogger<DashboardController> _logger;
    private readonly BHBqContext _context;

    public DashboardController(ILogger<DashboardController> logger)
    {
        _logger = logger;

            var options = new DbContextOptionsBuilder<BHBqContext>()
            .UseSqlite($"Data Source=BHBq.db")
            .Options;

        _context = new BHBqContext(options);
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

BHBq/Controllers/DocumentController.cs
using System.Diagnostics;
using BHBq.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace BHBq.Controllers;

public class DocumentController : Controller
{
    private readonly BHBqContext _context;
    public ClientViewModel Listes { get; set; }

    public DocumentController()
    {
        var options = new DbContextOptionsBuilder<BHBqContext>()
            .UseSqlite($"Data Source=BHBq.db")
            .Options;

        _context = new BHBqContext(options);
        Listes = new ClientViewModel();
    }

    //Get tous les documents
    public IActionResult Documents(int idProjet)
    {
        Listes.TargetProjet = _context.Projets.Find(idProjet);
        Listes.TargetClient = _context.Clients.Find(Listes.TargetProjet.IdClient);
        return View(Listes);
    }

    public IActionResult DocumentFlow(int idProjet)
    {
        Listes.TargetProjet = _context.Projets.Find(idProjet);
        Listes.TargetClient = _context.Clients.Find(Listes.TargetProjet.IdClient);

        // Récupérer les données de l'entreprise et des clients depuis la base de données
        var entreprises = _context.Entreprises.ToList();
        var listeEntreprises = entreprises
            .Select(
                e =>
                    new SelectListItem
                    {
                        Text = e.NomEntreprise, // Supposons que le nom de l'entreprise est stocké dans une propriété "Name"
                        Value = e.Id.ToString() // Supposons que l'ID de l'entreprise est stocké dans une propriété "Id"
                    }
            )
            .ToList();

        Listes.ListeEntreprises = listeEntreprises;

        return View(Listes);
    }

    [HttpPost]
    public async Task<IActionResult> EditDocument(int id, Document document, int Categorie)
    {
        var existingDocument = await _context.Documents.FindAsync(id);

        if (existingDocument == null)
        {
            return NotFound();
        }

        // Mettre à jour les propriétés non nulles de l'objet existant
        if (document.Type!=null)
        {
            existingDocument.Type = document.Type;
        }
        if (document.IdProjet != 0)
        {
            existingDocument.IdProjet = document.IdProjet;
        }
        if (document.IdAcompte != 0)
        {
            existingDocument.IdAcompte = document.IdAcompte;
        }
        if (document.IdTVA != 0)
        {
            existingDocument.IdTVA = document.IdTVA;
        }
        if (document.IdEntreprise != 0)
        {
            existingDocument.IdEntreprise = document.IdEntreprise;
        }
        if (document.Escompte != null)
        {
            existingDocument.Escompte = document.Escompte;
        }
        if (document.Origine != 0)
        {
            existingDocument.Origine = document.Origine;
        }
        if (!string.IsNullOrEmpty(document.Num))
        {
            existingDocument.Num = document.Num;
        }

        await _context.SaveChangesAsync();
        return RedirectToAction("Documents");
    }

    [HttpPost]
    public async Task<IActionResult> NewDocument(Document document, int Categorie)
    {
        await _context.Documents.AddAsync(document);
        await _context.SaveChangesAsync();
        return RedirectToAction("Documents");
    }

    [HttpPost]
    public async Task<IActionResult> DeleteDocument(int id)
    {
        var existingDocument = await _context.Documents.FindAsync(id);

        if (existingDocument == null)
        {
            return NotFound();
        }

        _context.Documents.Remove(existingDocument);
        await _context.SaveChangesAsync();

        return RedirectToAction("Documents");
    }
}

BHBq/Controllers/ProjetController.cs
using System.Diagnostics;
using BHBq.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace BHBq.Controllers;

public class ProjetController : Controller
{
    private readonly ILogger<ProjetController> _logger;
    private readonly BHBqContext _context;
    public ClientViewModel Listes { get; set; }

    public ProjetController(ILogger<ProjetController> logger)
    {
        _logger = logger;

        var options = new DbContextOptionsBuilder<BHBqContext>()
            .UseSqlite($"Data Source=BHBq.db")
            .Options;

        _context = new BHBqContext(options);
        Listes = new ClientViewModel();
    }

    //Get toutes les Projets
    public IActionResult Projets(int idClient)
    {
        Listes.TargetClient = _context.Clients.Find(idClient);

        return View(Listes);
    }

    public IActionResult Error(string Message)
    {
        ViewBag.Message = Message;
        ViewBag.Url = HttpContext.Request.Headers["Referer"];
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> NewProjet(Projet projet)
    {
        await _context.Projets.AddAsync(projet);
        await _context.SaveChangesAsync();
        return RedirectToAction("Projets", new { idClient = projet.IdClient });
    }

    [HttpPost]
    public async Task<IActionResult> DeleteProjet(int id)
    {
        var existingProjet = await _context.Projets.FindAsync(id);

        if (existingProjet == null)
        {
            return NotFound();
        }

        _context.Projets.Remove(existingProjet);
        await _context.SaveChangesAsync();

        return RedirectToAction("Projets", new { idClient = existingProjet.IdClient });
    }

    [HttpPost]
    public async Task<IActionResult> EditProjet(int id, Projet projet)
    {
        var existingProjet = await _context.Projets.FindAsync(id);

        if (existingProjet == null)
        {
            return NotFound();
        }

        // Copy the values from the projet object to the existing object only if the properties are not null
        if (projet.NomProjet != null)
        {
            existingProjet.NomProjet = projet.NomProjet;
        }
        if (projet.Etat != null)
        {
            existingProjet.Etat = projet.Etat;
        }
        if (projet.DateCreation != null)
        {
            existingProjet.DateCreation = projet.DateCreation;
        }
        if (projet.Description != null)
        {
            existingProjet.Description = projet.Description;
        }
        await _context.SaveChangesAsync();
        return RedirectToAction("Projets", new { idClient = existingProjet.IdClient });
    }

    public async Task<IActionResult> UpdateParams(int idProjet, List<string?> ValeurParametres)
    {
        var parametres = await _context.Parametres.Where(p => p.IdProjet == idProjet).ToListAsync();
        var existingProjet = await _context.Projets.FindAsync(idProjet);

        for (int i = 0; i < parametres.Count(); i++)
        {
            if (ValeurParametres[i] != null)
            {
                parametres[i].Valeur = ValeurParametres[i];
            }
        }

        if (existingProjet.Init == false)
        {
            existingProjet.Init = true;
        }

        await _context.SaveChangesAsync();
        return RedirectToAction("Projets", new { idClient = existingProjet.IdClient });
    }

    public async Task<IActionResult> CloneParams(int idProjet)
    {
        var existingProjet = await _context.Projets.FindAsync(idProjet);
        var originParams = await _context.Parametres.Where(p => p.Origine == null).ToListAsync();
        var projetParams = await _context.Parametres.Where(i => i.IdProjet == idProjet).ToListAsync();

        if (existingProjet != null && projetParams.Count == 0)
        {
            foreach (var param in originParams)
            {
                var clonedParameter = new Parametre
                {
                    Nom = param.Nom,
                    Origine = param.Id,
                    IdProjet = existingProjet.Id,
                    Explication = param.Explication,
                    Unite = param.Unite,
                };
                _context.Parametres.Add(clonedParameter);
            }
            await _context.SaveChangesAsync();
        }
        return RedirectToAction("ProjetParametre", new { idProjet = existingProjet.Id });
    }

    public IActionResult ProjetParametre(int idProjet)
    {
        Listes.TargetProjet = _context.Projets.Find(idProjet);
        Listes.TargetClient = _context.Clients.Find(Listes.TargetProjet.IdClient);

        return View(Listes);
    }
    public async Task<IActionResult> ResetParams(int idProjet)
    {
        var existingProjet = await _context.Projets.FindAsync(idProjet);
        var projectParams = await _context.Parametres.Where(p => p.IdProjet == idProjet).ToListAsync();

        if (existingProjet != null)
        {
            _context.Parametres.RemoveRange(projectParams);
            existingProjet.Init = false;
            await _context.SaveChangesAsync();
        }
        return RedirectToAction("Projets", new { idClient = existingProjet.IdClient });
    }

}

BHBq/Views/Document/DocumentFlow.cshtml
@model ClientViewModel
@{
    ViewData["Title"] = "Nouveau Document";
}
<h1>@ViewData["Title"]</h1>

<div class="pagetitle">
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a class="navbar-brand" asp-area="" asp-controller="Dashboard"
                    asp-action="Index">Dashboard</a>
            </li>
            <li class="breadcrumb-item"><a class="navbar-brand" asp-area="" asp-controller="Client"
                    asp-action="Clients">Clients</a>
            </li>
            <li class="breadcrumb-item"><a class="navbar-brand" asp-area="" asp-controller="Projet" asp-action="Projets"
                    asp-route-idClient="@Model.TargetClient.Id">Projets - @Model.TargetClient.Nom</a>
            </li>
            <li class="breadcrumb-item"><a class="navbar-brand" asp-area="" asp-controller="Document"
                    asp-action="Documents" asp-route-idProjet="@Model.TargetProjet.Id">Documents - Projet
                    @Model.TargetProjet.NomProjet</a>
            <li class="breadcrumb-item active">Paramètres - @Model.TargetProjet.NomProjet</li>
        </ol>
    </nav>
</div><!-- End Page Title -->

<div class="mb-5 p-4 bg-white shadow-sm">
    <h3>Création d'un nouveau document</h3>
    <div id="stepper1" class="bs-stepper linear">
        <div class="bs-stepper-header" role="tablist">
            <div class="step" data-target="#test-l-1">
                <button type="button" class="step-trigger" role="tab" id="stepper1trigger1" aria-controls="test-l-1"
                    aria-selected="false" disabled="disabled">
                    <span class="bs-stepper-circle">1</span>
                    <span class="bs-stepper-label">Type de document</span>
                </button>
            </div>
            <div class="bs-stepper-line"></div>
            <div class="step" data-target="#test-l-2">
                <button type="button" class="step-trigger" role="tab" id="stepper1trigger2" aria-controls="test-l-2"
                    aria-selected="false" disabled="disabled">
                    <span class="bs-stepper-circle">2</span>
                    <span class="bs-stepper-label">Choix de l'entreprise</span>
                </button>
            </div>
            <div class="bs-stepper-line"></div>
            <div class="step active" data-target="#test-l-3">
                <button type="button" class="step-trigger" role="tab" id="stepper1trigger3" aria-controls="test-l-3"
                    aria-selected="true">
                    <span class="bs-stepper-circle">3</span>
                    <span class="bs-stepper-label">Validate</span>
                </button>
            </div>
        </div>
        <div class="bs-stepper-content">
            <form method="post" class="needs-validation" asp-controller="Document" asp-action="NewDocument" novalidate>
                <div id="test-l-1" role="tabpanel" class="bs-stepper-pane" aria-labelledby="stepper1trigger1">

                    <select asp-for="@Model.TargetDocument.Type" class="form-select" id="form-stepper-1" name="Type"
                        aria-label="Default select example" required>
                        <option value="" selected>Choisissez un type de document</option>
                        <option value="0">Devis</option>
                        <option value="1">Acompte</option>
                        <option value="2">Solde</option>
                    </select>
                    <button class="btn btn-secondary btn-next-form m-2">Suivant</button>

                </div>

                <div id="test-l-2" role="tabpanel" class="bs-stepper-pane" aria-labelledby="stepper1trigger2">

                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label">Choix du client</label>
                        <div class="col-sm-10">
                            <select asp-for="@Model.TargetProjet.IdClient" asp-items="@Model.ListeEntreprises"
                                class="form-select" id="form-stepper-3" name="cli-2" aria-label="Default select example"
                                required>
                                <option value="" selected>Choisissez une entreprise</option>
                            </select>
                        </div>
                    </div>
                    <button class="btn btn-secondary btn-previous-form m-2"
                        onclick="stepper1.previous()">Précédent</button>
                    <button type="submit" class="btn btn-secondary btn-next-form m-2">Suivant</button>

                </div>

                <div id="test-l-3" role="tabpanel" class="bs-stepper-pane text-center active dstepper-block"
                    aria-labelledby="stepper1trigger3">



                    <button class="btn btn-primary mt-5" onclick="stepper1.previous()">Précédent</button>
                    <button type="submit" class="btn btn-primary mt-5">Sauvegarder</button>

                </div>
            </form>
        </div>
    </div>
</div>

BHBq/Views/Document/Documents.cshtml
@model ClientViewModel
@{
    ViewData["Title"] = "Documents";
}
<h1>@ViewData["Title"]</h1>

<div class="pagetitle">
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a class="navbar-brand" asp-area="" asp-controller="Dashboard"
                    asp-action="Index">Dashboard</a>
            </li>
            <li class="breadcrumb-item"><a class="navbar-brand" asp-area="" asp-controller="Client"
                    asp-action="Clients">Clients</a>
            </li>
            <li class="breadcrumb-item"><a class="navbar-brand" asp-area="" asp-controller="Projet"
                    asp-action="Projets" asp-route-idClient="@Model.TargetClient.Id">Projets - @Model.TargetClient.Nom</a>
            </li>
            <li class="breadcrumb-item active">Documents - Projet @Model.TargetProjet.NomProjet</li>
        </ol>
    </nav>
</div><!-- End Page Title -->



<section class="section contact">

    <div class="row">

        <!-- Ajouter un nouveau document -->
        <div class="col text-center m-4">
            <a asp-controller="Document" asp-action="DocumentFlow" asp-route-idProjet="@Model.TargetProjet.Id" class="info-box text-center btn btn-outline-secondary m-4">
                <i class="ri ri-add-line"></i>
                <h3>Nouveau Document</h3>
            </a>
        </div>
    </div>

    <div class="col">
        @foreach (var item in Model.Documents)
        {
            Model.TargetDocument = item;
            @await Html.PartialAsync("DocumentPartial/EditDocument")
        }
    </div>

    </div>

</section>