BHBq/Controllers/ClientController.cs
using System.Diagnostics;
using BHBq.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BHBq.Controllers;

public class ClientController : Controller
{
    private readonly BHBqContext _context;
    public ClientViewModel Listes { get; set; }

    public ClientController()
    {
        var options = new DbContextOptionsBuilder<BHBqContext>()
            .UseSqlite($"Data Source=BHBq.db")
            .Options;

        _context = new BHBqContext(options);
        Listes = new ClientViewModel();
    }

    //Get toutes les clients
    public IActionResult Clients()
    {
        return View(Listes);
    }

    [HttpPost]
    public async Task<IActionResult> EditClient(int id, Client client, int Categorie)
    {
        var existingClient = await _context.Clients.FindAsync(id);

        if (existingClient == null)
        {
            return NotFound();
        }

        // Mettre à jour les propriétés non nulles de l'objet existant
        if (!string.IsNullOrEmpty(client.Nom))
        {
            existingClient.Nom = client.Nom;
        }
        if (!string.IsNullOrEmpty(client.Adresse))
        {
            existingClient.Adresse = client.Adresse;
        }
        if (client.Categorie!=null)
        {
            existingClient.Categorie = Categorie == 1;
            if (client.Categorie == false)
            {
                existingClient.Siret = null;
                existingClient.TvaIntracom = null;
            }
        }

        // Mettre à jour les propriétés spécifiques aux professionnels
        if (client.Categorie == true)
        {
            if (!string.IsNullOrEmpty(client.Siret))
            {
                existingClient.Siret = client.Siret;
            }
            if (!string.IsNullOrEmpty(client.TvaIntracom))
            {
                existingClient.TvaIntracom = client.TvaIntracom;
            }
        }

        await _context.SaveChangesAsync();
        return RedirectToAction("Clients");
    }

    [HttpPost]
    public async Task<IActionResult> NewClient(Client client, int Categorie)
    {
        client.Categorie = Categorie == 1;
        await _context.Clients.AddAsync(client);
        await _context.SaveChangesAsync();
        return RedirectToAction("Clients");
    }

    [HttpPost]
    public async Task<IActionResult> DeleteClient(int id)
    {
        var existingClient = await _context.Clients.FindAsync(id);

        if (existingClient == null)
        {
            return NotFound();
        }

        // Supprimer tous les projets avec des IdClient égaux à id
        var projectsToDelete = await _context.Projets.Where(p => p.IdClient == id).ToListAsync();
        _context.Projets.RemoveRange(projectsToDelete);

        _context.Clients.Remove(existingClient);
        await _context.SaveChangesAsync();

        return RedirectToAction("Clients");
    }
    }

BHBq/Controllers/EntrepriseController.cs
using System.Diagnostics;
using BHBq.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BHBq.Controllers;

public class EntrepriseController : Controller
{
    private readonly BHBqContext _context;
    public List<Entreprise> entreprises { get; set; }
    public EntrepriseViewModel Listes { get; set; }

    public EntrepriseController()
    {
        var options = new DbContextOptionsBuilder<BHBqContext>()
            .UseSqlite($"Data Source=BHBq.db")
            .Options;

        _context = new BHBqContext(options);
        Listes = new EntrepriseViewModel();
    }

    //Get toutes les entreprises
    public IActionResult Entreprises()
    {
        return View(Listes);
    }

    [HttpPost]
    public async Task<IActionResult> EditEntreprise(int id, Entreprise entreprise)
    {
        var existingEntreprise = await _context.Entreprises.FindAsync(id);

        if (existingEntreprise == null)
        {
            return NotFound();
        }

        // Mettre à jour les propriétés non nulles de l'objet existant
        if (!string.IsNullOrEmpty(entreprise.NomEntreprise))
        {
            existingEntreprise.NomEntreprise = entreprise.NomEntreprise;
        }
        if (!string.IsNullOrEmpty(entreprise.Siret))
        {
            existingEntreprise.Siret = entreprise.Siret;
        }
        if (!string.IsNullOrEmpty(entreprise.Statut))
        {
            existingEntreprise.Statut = entreprise.Statut;
        }
        if (!string.IsNullOrEmpty(entreprise.Activite))
        {
            existingEntreprise.Activite = entreprise.Activite;
        }
        if (!string.IsNullOrEmpty(entreprise.Siege))
        {
            existingEntreprise.Siege = entreprise.Siege;
        }
        if (!string.IsNullOrEmpty(entreprise.APE))
        {
            existingEntreprise.APE = entreprise.APE;
        }
        existingEntreprise.Description = entreprise.Description;

        await _context.SaveChangesAsync();
        return RedirectToAction("Entreprises");
    }

    [HttpPost]
    public async Task<IActionResult> NewEntreprise(Entreprise entreprise)
    {
        if (!long.TryParse(entreprise.Siret, out _))
        {
            return RedirectToAction(
                "Error",
                "Error",
                new { Message = "Le siret doit être un nombre entier !" }
            );
        }
        else if (
            // Vérifie si les quatre premiers caractères sont des chiffres
            // Vérifie si le cinquième caractère est une lettre
            !char.IsDigit(entreprise.APE[0])
            || !char.IsDigit(entreprise.APE[1])
            || !char.IsDigit(entreprise.APE[2])
            || !char.IsDigit(entreprise.APE[3])
            || !char.IsLetter(entreprise.APE[4])
        )
        {
            return RedirectToAction(
                "Error",
                "Error",
                new { Message = "Le code APE rentré n'est pas au bon format !" }
            );
        }
        else
        {
            await _context.Entreprises.AddAsync(entreprise);
            await _context.SaveChangesAsync();
            return RedirectToAction("Entreprises");
        }
    }

    [HttpPost]
    public async Task<IActionResult> DeleteEntreprise(int id)
    {
        var existingEntreprise = await _context.Entreprises.FindAsync(id);

        if (existingEntreprise == null)
        {
            return NotFound();
        }

        _context.Entreprises.Remove(existingEntreprise);
        await _context.SaveChangesAsync();

        return RedirectToAction("Entreprises");
    }
}

BHBq/Controllers/ParametreController.cs
using System.Diagnostics;
using BHBq.Models;
using ElectronNET.API.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BHBq.Controllers;

public class ParametreController : Controller
{
    private readonly BHBqContext _context;
    public ParametreViewModel DataLink { get; set; }

    public ParametreController()
    {
        var options = new DbContextOptionsBuilder<BHBqContext>()
            .UseSqlite($"Data Source=BHBq.db")
            .Options;

        _context = new BHBqContext(options);
        DataLink = new ParametreViewModel();
    }

    //Get tous les parametres
    public IActionResult Parametres()
    {
        return View(DataLink);
    }

    //Display des parametres généraux
    public async Task<IActionResult> Global()
    {
        return View(DataLink);
    }

    [HttpPost]
    public async Task<IActionResult> EditParametre(int id, Parametre parametre)
    {
        var existingParametre = await _context.Parametres.FindAsync(id);

        if (existingParametre == null)
        {
            return NotFound();
        }

        // Mettre à jour les propriétés non nulles de l'objet existant
        if (!string.IsNullOrEmpty(parametre.Nom))
        {
            existingParametre.Nom = parametre.Nom;
        }
        if (!string.IsNullOrEmpty(parametre.Valeur))
        {
            existingParametre.Valeur = parametre.Valeur;
        }

        await _context.SaveChangesAsync();
        return RedirectToAction("Parametres");
    }

    [HttpPost]
    public async Task<IActionResult> NewParametre(Parametre parametre)
    {
        await _context.Parametres.AddAsync(parametre);
        await _context.SaveChangesAsync();
        return RedirectToAction("Parametres");
    }

    [HttpPost]
    public async Task<IActionResult> DeleteParametre(int id)
    {
        var existingParametre = await _context.Parametres.FindAsync(id);

        if (existingParametre == null)
        {
            return NotFound();
        }

        _context.Parametres.Remove(existingParametre);
        await _context.SaveChangesAsync();

        return RedirectToAction("Parametres");
    }

    [HttpPost]
    public async Task<IActionResult> EditTVA(int id, TVA tva)
    {
        var existingTVA = await _context.TVAs.FindAsync(id);

        if (existingTVA == null)
        {
            return NotFound();
        }

        // Mettre à jour les propriétés non nulles de l'objet existant
        if (!string.IsNullOrEmpty(tva.Code))
        {
            existingTVA.Code = tva.Code;
        }
        if (!string.IsNullOrEmpty(tva.Taux))
        {
            existingTVA.Taux = tva.Taux;
        }

        await _context.SaveChangesAsync();
        return RedirectToAction("Global");
    }

    [HttpPost]
    public async Task<IActionResult> NewTVA(TVA tva)
    {
        await _context.TVAs.AddAsync(tva);
        await _context.SaveChangesAsync();
        return RedirectToAction("Global");
    }

    [HttpPost]
    public async Task<IActionResult> DeleteTVA(int id)
    {
        var existingTVA = await _context.TVAs.FindAsync(id);

        if (existingTVA == null)
        {
            return NotFound();
        }

        _context.TVAs.Remove(existingTVA);
        await _context.SaveChangesAsync();

        return RedirectToAction("Global");
    }

    public async Task<IActionResult> EditAcompte(string id, GammeAcompte gammeAcompte)
    {
        var existingGammeAcompte = await _context.GammeAcomptes.FindAsync(id);

        if (existingGammeAcompte == null)
        {
            return NotFound();
        }

        // Mettre à jour les propriétés non nulles de l'objet existant
        if (!string.IsNullOrEmpty(gammeAcompte.Pourcentage1))
        {
            existingGammeAcompte.Pourcentage1 = gammeAcompte.Pourcentage1;
        }
        if (!string.IsNullOrEmpty(gammeAcompte.Pourcentage2))
        {
            existingGammeAcompte.Pourcentage2 = gammeAcompte.Pourcentage2;
        }
        if (!string.IsNullOrEmpty(gammeAcompte.Pourcentage3))
        {
            existingGammeAcompte.Pourcentage3 = gammeAcompte.Pourcentage3;
        }
        if (!string.IsNullOrEmpty(gammeAcompte.Pourcentage4))
        {
            existingGammeAcompte.Pourcentage4 = gammeAcompte.Pourcentage4;
        }
        if (!string.IsNullOrEmpty(gammeAcompte.Pourcentage5))
        {
            existingGammeAcompte.Pourcentage5 = gammeAcompte.Pourcentage5;
        }

        await _context.SaveChangesAsync();
        return RedirectToAction("Global");
    }

    [HttpPost]
    public async Task<IActionResult> NewAcompte(GammeAcompte gammeAcompte)
    {
        await _context.GammeAcomptes.AddAsync(gammeAcompte);
        await _context.SaveChangesAsync();
        return RedirectToAction("Global");
    }

    [HttpPost]
    public async Task<IActionResult> DeleteAcompte(string id)
    {
        var existingGammeAcompte = await _context.GammeAcomptes.FindAsync(id);

        if (existingGammeAcompte == null)
        {
            return NotFound();
        }

        _context.GammeAcomptes.Remove(existingGammeAcompte);
        await _context.SaveChangesAsync();

        return RedirectToAction("Global");
    }
}

BHBq/Views/Shared/EditEntreprise.cshtml
@model Entreprise
@{string modalId = $"myModal-{Model.Id}";}

<div class="container-fluid text-end">
    <form asp-area="" asp-controller="Entreprise" asp-action="DeleteEntreprise" asp-route-id="@Model.Id" method="post"
        onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette entreprise?');">
        <button type="submit" class="btn btn-outline-dark"><i class="ri-delete-bin-2-line fs-4"></i></button>
    </form>
</div>
<div class="info-box card">
    <i class="bi bi-geo-alt"></i>
    <h3>@Model.NomEntreprise</h3>
    <p>@Model.Activite</p>
    <button class="btn btn-outline-dark btn-sm mt-4" type="button" data-bs-toggle="modal"
        data-bs-target="@($"#{modalId}")">Modifier les informations</button>

    <div class="modal fade" id="@modalId" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Mise à jour des informations de @Model.NomEntreprise</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="post" class="row g-3" asp-controller="Entreprise" asp-action="EditEntreprise"
                        asp-route-Id="@Model.Id">
                        <div class="col-md-12">
                            <input asp-for="@Model.NomEntreprise" type="text" class="form-control"
                                placeholder="Nom de l'entreprise" name="nomEntreprise" required>
                        </div>
                        <div class="col-md-6">
                            <input asp-for="@Model.Siret" type="text" class="form-control" placeholder="Siret"
                                name="siret" required>
                        </div>
                        <div class="col-md-6">
                            <input asp-for="@Model.Siege" type="text" class="form-control" placeholder="Siege"
                                name="siege" required>
                        </div>
                        <div class="col-12">
                            <input asp-for="@Model.Activite" type="text" class="form-control" placeholder="Activite"
                                name="activite" required>
                        </div>
                        <div class="col-md-6">
                            <input asp-for="@Model.APE" type="text" class="form-control" placeholder="APE" name="ape"
                                required>
                        </div>
                        <div class="col-md-6">
                            <input asp-for="@Model.Statut" type="text" class="form-control" placeholder="Statut"
                                name="statut" required>
                        </div>
                        <div class="col-12">
                            <div class="form-floating">
                                <textarea asp-for="@Model.Description" class="form-control" id="floatingTextarea"
                                    style="height: 100px;"></textarea>
                                <label for="floatingTextarea">Description</label>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Abandonner</button>
                            <button type="submit" class="btn btn-success">Sauvegarder</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div><!-- Fin du Modal centré verticalement -->
</div>

BHBq/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>@ViewData["Title"] - BHBq</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="~/assets/img/LogoBHBqIcon.png" asp-append-version="true" rel="icon">
  <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="~/assets/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">
  <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="~/assets/vendor/quill/quill.snow.css" rel="stylesheet">
  <link href="~/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
  <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="~/assets/vendor/simple-datatables/style.css" rel="stylesheet">
  <link rel="stylesheet" href="~/BHBq.styles.css" asp-append-version="true" />

  <!-- Template Main CSS File -->
  <link href="~/assets/css/style.css" rel="stylesheet" asp-append-version="true">

  <!-- Stepper -->
  <link href="~/lib/bs-stepper/dist/css/bs-stepper.css" rel="stylesheet" asp-append-version="true">
</head>

<body>
  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <i class="bi bi-list toggle-sidebar-btn"></i>
      <a href="index.html" class="logo d-flex align-items-center m-4">
        <img src="assets/img/LogoBHBqIcon.png" alt="">
        <span class="d-none d-lg-block">BHB Quote</span>
      </a>

    </div><!-- End Logo -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <i class="bi bi-gear fs-4"></i>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>Paramètres</h6>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a asp-controller="Parametre" asp-action="Parametres" class="dropdown-item d-flex align-items-center">
                <i class="bi bi-diagram-2"></i>
                <span>Modélisation</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a asp-controller="Parametre" asp-action="Global" class="dropdown-item d-flex align-items-center">
                <i class="bi bi-gear"></i>
                <span>Paramètres Généraux</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Header Nav -->

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link collapsed" asp-area="" asp-controller="Entreprise" asp-action="Entreprises"><i
            class="bi bi-building"></i><span>Entreprises</span></a>
      </li><!-- End Entreprises Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" asp-area="" asp-controller="Client" asp-action="Clients"><i
            class="bi bi-person"></i><span>Clients</span></a>
      </li><!-- End Clients Nav -->

    </ul>
  </aside><!-- End Sidebar-->

  <main id="main" role="main" class="main">
    @RenderBody()
  </main>

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="credits">
      Un produit BHB-Groupe - Designed by Gabin Mobétie
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
      class="bi bi-arrow-up-short"></i></a>
  <!-- ... -->

  <!-- Vendor JS Files -->
  <script src="~/assets/vendor/apexcharts/apexcharts.min.js" asp-append-version="true"></script>
  <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
  <script src="~/assets/vendor/chart.js/chart.umd.js" asp-append-version="true"></script>
  <script src="~/assets/vendor/echarts/echarts.min.js" asp-append-version="true"></script>
  <script src="~/assets/vendor/quill/quill.min.js" asp-append-version="true"></script>
  <script src="~/assets/vendor/simple-datatables/simple-datatables.js" asp-append-version="true"></script>
  <script src="~/assets/vendor/tinymce/tinymce.min.js" asp-append-version="true"></script>
  <script src="~/assets/vendor/php-email-form/validate.js" asp-append-version="true"></script>
  <script src="~/assets/js/main.js" asp-append-version="true"></script>
  <script src="~/lib/bs-stepper/dist/js/bs-stepper.js" asp-append-version="true"></script>
  @await RenderSectionAsync("Scripts", required: false)
</body>

</html>